// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: army.proto

package protos

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type Armys struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Common *Common `protobuf:"bytes,1,opt,name=common,proto3" json:"common,omitempty"`
	Army   []*Army `protobuf:"bytes,2,rep,name=army,proto3" json:"army,omitempty"`
}

func (x *Armys) Reset() {
	*x = Armys{}
	if protoimpl.UnsafeEnabled {
		mi := &file_army_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Armys) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Armys) ProtoMessage() {}

func (x *Armys) ProtoReflect() protoreflect.Message {
	mi := &file_army_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Armys.ProtoReflect.Descriptor instead.
func (*Armys) Descriptor() ([]byte, []int) {
	return file_army_proto_rawDescGZIP(), []int{0}
}

func (x *Armys) GetCommon() *Common {
	if x != nil {
		return x.Common
	}
	return nil
}

func (x *Armys) GetArmy() []*Army {
	if x != nil {
		return x.Army
	}
	return nil
}

type Army struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ArmyId  int32 `protobuf:"varint,1,opt,name=armyId,proto3" json:"armyId,omitempty"`
	ArmyNum int32 `protobuf:"varint,2,opt,name=armyNum,proto3" json:"armyNum,omitempty"`
}

func (x *Army) Reset() {
	*x = Army{}
	if protoimpl.UnsafeEnabled {
		mi := &file_army_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Army) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Army) ProtoMessage() {}

func (x *Army) ProtoReflect() protoreflect.Message {
	mi := &file_army_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Army.ProtoReflect.Descriptor instead.
func (*Army) Descriptor() ([]byte, []int) {
	return file_army_proto_rawDescGZIP(), []int{1}
}

func (x *Army) GetArmyId() int32 {
	if x != nil {
		return x.ArmyId
	}
	return 0
}

func (x *Army) GetArmyNum() int32 {
	if x != nil {
		return x.ArmyNum
	}
	return 0
}

var File_army_proto protoreflect.FileDescriptor

var file_army_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x61, 0x72, 0x6d, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x0c, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x43, 0x0a, 0x05, 0x41, 0x72,
	0x6d, 0x79, 0x73, 0x12, 0x1f, 0x0a, 0x06, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x07, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x52, 0x06, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x04, 0x61, 0x72, 0x6d, 0x79, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x05, 0x2e, 0x41, 0x72, 0x6d, 0x79, 0x52, 0x04, 0x61, 0x72, 0x6d, 0x79, 0x22,
	0x38, 0x0a, 0x04, 0x41, 0x72, 0x6d, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x72, 0x6d, 0x79, 0x49,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x72, 0x6d, 0x79, 0x49, 0x64, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x72, 0x6d, 0x79, 0x4e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x61, 0x72, 0x6d, 0x79, 0x4e, 0x75, 0x6d, 0x42, 0x08, 0x5a, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_army_proto_rawDescOnce sync.Once
	file_army_proto_rawDescData = file_army_proto_rawDesc
)

func file_army_proto_rawDescGZIP() []byte {
	file_army_proto_rawDescOnce.Do(func() {
		file_army_proto_rawDescData = protoimpl.X.CompressGZIP(file_army_proto_rawDescData)
	})
	return file_army_proto_rawDescData
}

var file_army_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_army_proto_goTypes = []interface{}{
	(*Armys)(nil),  // 0: Armys
	(*Army)(nil),   // 1: Army
	(*Common)(nil), // 2: Common
}
var file_army_proto_depIdxs = []int32{
	2, // 0: Armys.common:type_name -> Common
	1, // 1: Armys.army:type_name -> Army
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_army_proto_init() }
func file_army_proto_init() {
	if File_army_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_army_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Armys); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_army_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Army); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_army_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_army_proto_goTypes,
		DependencyIndexes: file_army_proto_depIdxs,
		MessageInfos:      file_army_proto_msgTypes,
	}.Build()
	File_army_proto = out.File
	file_army_proto_rawDesc = nil
	file_army_proto_goTypes = nil
	file_army_proto_depIdxs = nil
}
